FROM centos:latest
MAINTAINER septnn septnn@sina.com
# RUN yum -y install gcc gcc-c++ openssl openssl-devel zlib zlib-devel nginx supervisor
EXPOSE 80
# RUN rm -rf /var/lib/yum/history/*.sqlite && rm -rf /var/cache/yum
WORKDIR /home/juewei
VOLUME /home/juewei